exclude: [
    "README.md",
    "utils",
    "smart_common"
]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis",  "autolink", "strikethrough", "fenced_code"]

production_url: http://docs-v06.smartplatforms.org
